### ISSUE TITLE
find: bash error when completing argument before `-exec`

### ISSUE THREAD

**Issue by fbriere** [scop/bash-completion#509]
With a command line such as `find xyz -exec ...`, attempting to complete the `xyz` argument results in a bash error: `COMP_POINT: substring expression < 0`.

(It does not seem to matter whether the argument would actually match something.)

**Comment by scop** [comment]
I cannot reproduce. OS, bash, and bash-completion versions? See also the Troubleshooting section of README.md, and attach the resulting `set -x` output here (after reviewing that it does not contain anything you don't want to share in public).

**Comment by fbriere** [comment]
My apologies for filing an incomplete bug report.  (I know how frustrating those can be.)

This was initially encountered with 2.11 on Debian/testing (bash 5.1.4(1)-release).  That said, I can also reproduce this bug by installing 2.11 on other releases, going as far back as Debian/jessie (4.3.30(1)-release) and Ubuntu/trusty (4.3.8(1)-release).

I'm attaching the `set -x` output as [issue-509.txt](https://github.com/scop/bash-completion/files/6174419/issue-509.txt).

For the record, I've bisected this down to 3e849c2.  Kind of an obvious suspect in retrospect.  :smile:

And just in case I didn't phrase this clearly, the issue is with this: `find xyz<Tab> -exec`.  In other words, `-exec` must already be present on the command line for the previous argument expansion to fail.

**Comment by scop** [comment]
Ah, thanks for the clarification, reproduced now, looking into it.

**Comment by scop** [comment]
Should be fixed now. Unfortunately we don't have an easy way to test for cases like this for commands (there is some help for unit tests), so test suite not touched here.

**Comment by leisti** [comment]
I just reproduced this bug (and found this bug report by googling).

Steps to reproduce:

Assumptions: the current working directory includes subdirectories ABC and DEF.

1. Type this command on the Bash command line: `find ABC -type f -exec chmod a-w {} \;`
2. Use the up arrow to bring up the previous command.
3. Delete the text `ABC`
4. Type `DE`
5. Press the tab key.

Expected result: `DE` completed to `DEF`.

Observed result: Bash outputs: `find DEbash: COMP_POINT: substring expression < 0`

Environment: Xubuntu 21.10, xfce4-terminal, Bash version "GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)"

**Comment by scop** [comment]
I cannot reproduce that with current git master. So before opening a new bug report -- definitely do that if there is still reason to, with full requested details, this one was closed with a fix ~20 months ago -- make sure to test with the latest from the master branch or at least the latest release (there was no into about the bash-completion version in your comment).

**Comment by leisti** [comment]
Sorry, forgot the bash-completion version: it's 1:2.11-2ubuntu1. From the table at https://repology.org/project/bash-completion/versions it seems that's the latest release? So, I'll create a new bug report.

**Comment by amir1376irani** [comment]
still not fixed!
exactly reproduced same as @leisti

Ubuntu desktop 22.04.3
uname -a : Linux ubuntu 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
find -version : find (GNU findutils) 4.8.0
bash-completion : 1:2.11-5ubuntu1

**Comment by leisti** [comment]
I can still reproduce this in exactly the same way as in my comment in November 2021.

Environment:
- OS: Linux Mint, version 21.2
- terminal: gnome-terminal, version 3.44.0+mint1+vanessa
- package bash: version 5.1-6ubuntu1
- package bash-completion: version 1:2.11-5ubuntu1

**Comment by akinomyoga** [comment]
The fix just hasn't been released as mentioned in #757.

We started refactoring the API for external completions but haven't yet completed it. Currently, the old and new APIs are mixed. Even worse, the new APIs are not yet fully determined and still subject to change. For compatibility with [external completions](https://github.com/scop/bash-completion/wiki/Externally-available-completions), we cannot release the new version with the temporary APIs. However, we don't have a sufficient number of skilled reviewers who have sufficient time to work on it intensively. It will take time, probably about one more year.

If you can contribute, please check the remaining tasks at https://github.com/scop/bash-completion/projects/2.

Hopefully, #1037, #1051, and #987 are the last set of changes needed to finalize the design of the new API. The other ones would be mostly internal things that don't affect the interface to external completions, so I guess we can technically process them after the release of 2.12.

If you cannot wait, please use the latest `master`. There shouldn't be problems in using the `master` version unless you are a writer of external completions. Or, you might ask the package maintainer of your distribution if it is possible to cherry-pick a patch f1ddf810e4ee6693acb9fab1be1794586aa111a0.

**Comment by leisti** [comment]
Good to know there's already a fix. I guess we'll just have to wait for Ubuntu and Linux Mint to pick up the fixed version. In the meanwhile, it's a pretty minor bug, so can be lived with.

**Comment by ipaqmaster** [comment]
Experiencing this on bash-completion 2.11-3 with `bash 5.2.021-1` on Archlinux. For probably a few months now I've had to avoid tabbing when typing the directory for a `find` command.
